#!/usr/bin/env php
<?php

require 'src/Helper/DirectoryHelper.php';
require 'autoloader.php';

use Symfony\Component\Console\Application;
use Etre\Shell\Console\Commands\PatchCommand;
use Etre\Shell\Console\Commands\PlayCommand;
use Etre\Shell\Console\Commands\Installer\RecoverCommand as InstallerRecoverCommand;
use Etre\Shell\Console\Commands\Installer\RunCommand as InstallerRunCommand;

$application = new Application();

$application->add(new PatchCommand());
$application->add(new PlayCommand());
$application->add(new InstallerRunCommand());
$application->add(new InstallerRecoverCommand());

$application->run();